/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerOnboardSchoolRouteImport } from './routes/manager.onboard-school'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerOnboardSchoolRoute = ManagerOnboardSchoolRouteImport.update({
  id: '/onboard-school',
  path: '/onboard-school',
  getParentRoute: () => ManagerRoute,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/manager': typeof ManagerRouteWithChildren
  '/school': typeof SchoolRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRoute
  '/teacher': typeof TeacherRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/manager/onboard-school': typeof ManagerOnboardSchoolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/manager': typeof ManagerRouteWithChildren
  '/school': typeof SchoolRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRoute
  '/teacher': typeof TeacherRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/manager/onboard-school': typeof ManagerOnboardSchoolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/manager': typeof ManagerRouteWithChildren
  '/school': typeof SchoolRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRoute
  '/teacher': typeof TeacherRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/manager/onboard-school': typeof ManagerOnboardSchoolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/console'
    | '/manager'
    | '/school'
    | '/sitemap.xml'
    | '/student'
    | '/teacher'
    | '/learn/$slug'
    | '/manager/onboard-school'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/console'
    | '/manager'
    | '/school'
    | '/sitemap.xml'
    | '/student'
    | '/teacher'
    | '/learn/$slug'
    | '/manager/onboard-school'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/console'
    | '/manager'
    | '/school'
    | '/sitemap.xml'
    | '/student'
    | '/teacher'
    | '/learn/$slug'
    | '/manager/onboard-school'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ConsoleRoute: typeof ConsoleRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  SchoolRoute: typeof SchoolRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentRoute: typeof StudentRoute
  TeacherRoute: typeof TeacherRoute
  LearnSlugRoute: typeof LearnSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/onboard-school': {
      id: '/manager/onboard-school'
      path: '/onboard-school'
      fullPath: '/manager/onboard-school'
      preLoaderRoute: typeof ManagerOnboardSchoolRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ManagerRouteChildren {
  ManagerOnboardSchoolRoute: typeof ManagerOnboardSchoolRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerOnboardSchoolRoute: ManagerOnboardSchoolRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ConsoleRoute: ConsoleRoute,
  ManagerRoute: ManagerRouteWithChildren,
  SchoolRoute: SchoolRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentRoute: StudentRoute,
  TeacherRoute: TeacherRoute,
  LearnSlugRoute: LearnSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
