/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SetupSecurityRouteImport } from './routes/setup-security'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as SalesRepRouteImport } from './routes/sales-rep'
import { Route as RegisterSchoolRouteImport } from './routes/register-school'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchoolIndexRouteImport } from './routes/school.index'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as TeacherQuizzesRouteImport } from './routes/teacher.quizzes'
import { Route as TeacherAssignmentsRouteImport } from './routes/teacher.assignments'
import { Route as StudentQuizzesRouteImport } from './routes/student.quizzes'
import { Route as StudentAssignmentsRouteImport } from './routes/student.assignments'
import { Route as SettingsChangePasswordRouteImport } from './routes/settings.change-password'
import { Route as SchoolCreateTeacherRouteImport } from './routes/school.create-teacher'
import { Route as SchoolBulkStudentsRouteImport } from './routes/school.bulk-students'
import { Route as ManagerUsersRouteImport } from './routes/manager.users'
import { Route as ManagerSalesHierarchyRouteImport } from './routes/manager.sales-hierarchy'
import { Route as ManagerPendingSchoolsRouteImport } from './routes/manager.pending-schools'
import { Route as ManagerOnboardSchoolRouteImport } from './routes/manager.onboard-school'
import { Route as ManagerCreateSalesRepRouteImport } from './routes/manager.create-sales-rep'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSalesHierarchyRouteImport } from './routes/admin.sales-hierarchy'
import { Route as AdminPendingSchoolsRouteImport } from './routes/admin.pending-schools'
import { Route as AdminDirectoryRouteImport } from './routes/admin.directory'
import { Route as AdminCreateSalesRepRouteImport } from './routes/admin.create-sales-rep'
import { Route as ApiPublicSchoolRegistrationsRouteImport } from './routes/api/public/school-registrations'
import { Route as ApiPublicSalesRepsRouteImport } from './routes/api/public/sales-reps'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupSecurityRoute = SetupSecurityRouteImport.update({
  id: '/setup-security',
  path: '/setup-security',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRepRoute = SalesRepRouteImport.update({
  id: '/sales-rep',
  path: '/sales-rep',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSchoolRoute = RegisterSchoolRouteImport.update({
  id: '/register-school',
  path: '/register-school',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolIndexRoute = SchoolIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchoolRoute,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const TeacherQuizzesRoute = TeacherQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAssignmentsRoute = TeacherAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentQuizzesRoute = StudentQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssignmentsRoute = StudentAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => StudentRoute,
} as any)
const SettingsChangePasswordRoute = SettingsChangePasswordRouteImport.update({
  id: '/settings/change-password',
  path: '/settings/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolCreateTeacherRoute = SchoolCreateTeacherRouteImport.update({
  id: '/create-teacher',
  path: '/create-teacher',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolBulkStudentsRoute = SchoolBulkStudentsRouteImport.update({
  id: '/bulk-students',
  path: '/bulk-students',
  getParentRoute: () => SchoolRoute,
} as any)
const ManagerUsersRoute = ManagerUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerSalesHierarchyRoute = ManagerSalesHierarchyRouteImport.update({
  id: '/sales-hierarchy',
  path: '/sales-hierarchy',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerPendingSchoolsRoute = ManagerPendingSchoolsRouteImport.update({
  id: '/pending-schools',
  path: '/pending-schools',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerOnboardSchoolRoute = ManagerOnboardSchoolRouteImport.update({
  id: '/onboard-school',
  path: '/onboard-school',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerCreateSalesRepRoute = ManagerCreateSalesRepRouteImport.update({
  id: '/create-sales-rep',
  path: '/create-sales-rep',
  getParentRoute: () => ManagerRoute,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesHierarchyRoute = AdminSalesHierarchyRouteImport.update({
  id: '/sales-hierarchy',
  path: '/sales-hierarchy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPendingSchoolsRoute = AdminPendingSchoolsRouteImport.update({
  id: '/pending-schools',
  path: '/pending-schools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDirectoryRoute = AdminDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreateSalesRepRoute = AdminCreateSalesRepRouteImport.update({
  id: '/create-sales-rep',
  path: '/create-sales-rep',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicSchoolRegistrationsRoute =
  ApiPublicSchoolRegistrationsRouteImport.update({
    id: '/api/public/school-registrations',
    path: '/api/public/school-registrations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSalesRepsRoute = ApiPublicSalesRepsRouteImport.update({
  id: '/api/public/sales-reps',
  path: '/api/public/sales-reps',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/manager': typeof ManagerRouteWithChildren
  '/register-school': typeof RegisterSchoolRoute
  '/sales-rep': typeof SalesRepRoute
  '/school': typeof SchoolRouteWithChildren
  '/setup-security': typeof SetupSecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/create-sales-rep': typeof AdminCreateSalesRepRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/pending-schools': typeof AdminPendingSchoolsRoute
  '/admin/sales-hierarchy': typeof AdminSalesHierarchyRoute
  '/admin/users': typeof AdminUsersRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/manager/create-sales-rep': typeof ManagerCreateSalesRepRoute
  '/manager/onboard-school': typeof ManagerOnboardSchoolRoute
  '/manager/pending-schools': typeof ManagerPendingSchoolsRoute
  '/manager/sales-hierarchy': typeof ManagerSalesHierarchyRoute
  '/manager/users': typeof ManagerUsersRoute
  '/school/bulk-students': typeof SchoolBulkStudentsRoute
  '/school/create-teacher': typeof SchoolCreateTeacherRoute
  '/settings/change-password': typeof SettingsChangePasswordRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/quizzes': typeof TeacherQuizzesRoute
  '/manager/': typeof ManagerIndexRoute
  '/school/': typeof SchoolIndexRoute
  '/api/public/sales-reps': typeof ApiPublicSalesRepsRoute
  '/api/public/school-registrations': typeof ApiPublicSchoolRegistrationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register-school': typeof RegisterSchoolRoute
  '/sales-rep': typeof SalesRepRoute
  '/setup-security': typeof SetupSecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/create-sales-rep': typeof AdminCreateSalesRepRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/pending-schools': typeof AdminPendingSchoolsRoute
  '/admin/sales-hierarchy': typeof AdminSalesHierarchyRoute
  '/admin/users': typeof AdminUsersRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/manager/create-sales-rep': typeof ManagerCreateSalesRepRoute
  '/manager/onboard-school': typeof ManagerOnboardSchoolRoute
  '/manager/pending-schools': typeof ManagerPendingSchoolsRoute
  '/manager/sales-hierarchy': typeof ManagerSalesHierarchyRoute
  '/manager/users': typeof ManagerUsersRoute
  '/school/bulk-students': typeof SchoolBulkStudentsRoute
  '/school/create-teacher': typeof SchoolCreateTeacherRoute
  '/settings/change-password': typeof SettingsChangePasswordRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/quizzes': typeof TeacherQuizzesRoute
  '/manager': typeof ManagerIndexRoute
  '/school': typeof SchoolIndexRoute
  '/api/public/sales-reps': typeof ApiPublicSalesRepsRoute
  '/api/public/school-registrations': typeof ApiPublicSchoolRegistrationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/manager': typeof ManagerRouteWithChildren
  '/register-school': typeof RegisterSchoolRoute
  '/sales-rep': typeof SalesRepRoute
  '/school': typeof SchoolRouteWithChildren
  '/setup-security': typeof SetupSecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/create-sales-rep': typeof AdminCreateSalesRepRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/pending-schools': typeof AdminPendingSchoolsRoute
  '/admin/sales-hierarchy': typeof AdminSalesHierarchyRoute
  '/admin/users': typeof AdminUsersRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/manager/create-sales-rep': typeof ManagerCreateSalesRepRoute
  '/manager/onboard-school': typeof ManagerOnboardSchoolRoute
  '/manager/pending-schools': typeof ManagerPendingSchoolsRoute
  '/manager/sales-hierarchy': typeof ManagerSalesHierarchyRoute
  '/manager/users': typeof ManagerUsersRoute
  '/school/bulk-students': typeof SchoolBulkStudentsRoute
  '/school/create-teacher': typeof SchoolCreateTeacherRoute
  '/settings/change-password': typeof SettingsChangePasswordRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/quizzes': typeof TeacherQuizzesRoute
  '/manager/': typeof ManagerIndexRoute
  '/school/': typeof SchoolIndexRoute
  '/api/public/sales-reps': typeof ApiPublicSalesRepsRoute
  '/api/public/school-registrations': typeof ApiPublicSchoolRegistrationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/console'
    | '/forgot-password'
    | '/manager'
    | '/register-school'
    | '/sales-rep'
    | '/school'
    | '/setup-security'
    | '/sitemap.xml'
    | '/student'
    | '/teacher'
    | '/admin/create-sales-rep'
    | '/admin/directory'
    | '/admin/pending-schools'
    | '/admin/sales-hierarchy'
    | '/admin/users'
    | '/learn/$slug'
    | '/manager/create-sales-rep'
    | '/manager/onboard-school'
    | '/manager/pending-schools'
    | '/manager/sales-hierarchy'
    | '/manager/users'
    | '/school/bulk-students'
    | '/school/create-teacher'
    | '/settings/change-password'
    | '/student/assignments'
    | '/student/quizzes'
    | '/teacher/assignments'
    | '/teacher/quizzes'
    | '/manager/'
    | '/school/'
    | '/api/public/sales-reps'
    | '/api/public/school-registrations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/console'
    | '/forgot-password'
    | '/register-school'
    | '/sales-rep'
    | '/setup-security'
    | '/sitemap.xml'
    | '/student'
    | '/teacher'
    | '/admin/create-sales-rep'
    | '/admin/directory'
    | '/admin/pending-schools'
    | '/admin/sales-hierarchy'
    | '/admin/users'
    | '/learn/$slug'
    | '/manager/create-sales-rep'
    | '/manager/onboard-school'
    | '/manager/pending-schools'
    | '/manager/sales-hierarchy'
    | '/manager/users'
    | '/school/bulk-students'
    | '/school/create-teacher'
    | '/settings/change-password'
    | '/student/assignments'
    | '/student/quizzes'
    | '/teacher/assignments'
    | '/teacher/quizzes'
    | '/manager'
    | '/school'
    | '/api/public/sales-reps'
    | '/api/public/school-registrations'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/console'
    | '/forgot-password'
    | '/manager'
    | '/register-school'
    | '/sales-rep'
    | '/school'
    | '/setup-security'
    | '/sitemap.xml'
    | '/student'
    | '/teacher'
    | '/admin/create-sales-rep'
    | '/admin/directory'
    | '/admin/pending-schools'
    | '/admin/sales-hierarchy'
    | '/admin/users'
    | '/learn/$slug'
    | '/manager/create-sales-rep'
    | '/manager/onboard-school'
    | '/manager/pending-schools'
    | '/manager/sales-hierarchy'
    | '/manager/users'
    | '/school/bulk-students'
    | '/school/create-teacher'
    | '/settings/change-password'
    | '/student/assignments'
    | '/student/quizzes'
    | '/teacher/assignments'
    | '/teacher/quizzes'
    | '/manager/'
    | '/school/'
    | '/api/public/sales-reps'
    | '/api/public/school-registrations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConsoleRoute: typeof ConsoleRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  RegisterSchoolRoute: typeof RegisterSchoolRoute
  SalesRepRoute: typeof SalesRepRoute
  SchoolRoute: typeof SchoolRouteWithChildren
  SetupSecurityRoute: typeof SetupSecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  LearnSlugRoute: typeof LearnSlugRoute
  SettingsChangePasswordRoute: typeof SettingsChangePasswordRoute
  ApiPublicSalesRepsRoute: typeof ApiPublicSalesRepsRoute
  ApiPublicSchoolRegistrationsRoute: typeof ApiPublicSchoolRegistrationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-security': {
      id: '/setup-security'
      path: '/setup-security'
      fullPath: '/setup-security'
      preLoaderRoute: typeof SetupSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-rep': {
      id: '/sales-rep'
      path: '/sales-rep'
      fullPath: '/sales-rep'
      preLoaderRoute: typeof SalesRepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-school': {
      id: '/register-school'
      path: '/register-school'
      fullPath: '/register-school'
      preLoaderRoute: typeof RegisterSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school/': {
      id: '/school/'
      path: '/'
      fullPath: '/school/'
      preLoaderRoute: typeof SchoolIndexRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/teacher/quizzes': {
      id: '/teacher/quizzes'
      path: '/quizzes'
      fullPath: '/teacher/quizzes'
      preLoaderRoute: typeof TeacherQuizzesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/assignments': {
      id: '/teacher/assignments'
      path: '/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof TeacherAssignmentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/quizzes': {
      id: '/student/quizzes'
      path: '/quizzes'
      fullPath: '/student/quizzes'
      preLoaderRoute: typeof StudentQuizzesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assignments': {
      id: '/student/assignments'
      path: '/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof StudentAssignmentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/settings/change-password': {
      id: '/settings/change-password'
      path: '/settings/change-password'
      fullPath: '/settings/change-password'
      preLoaderRoute: typeof SettingsChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school/create-teacher': {
      id: '/school/create-teacher'
      path: '/create-teacher'
      fullPath: '/school/create-teacher'
      preLoaderRoute: typeof SchoolCreateTeacherRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/bulk-students': {
      id: '/school/bulk-students'
      path: '/bulk-students'
      fullPath: '/school/bulk-students'
      preLoaderRoute: typeof SchoolBulkStudentsRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/manager/users': {
      id: '/manager/users'
      path: '/users'
      fullPath: '/manager/users'
      preLoaderRoute: typeof ManagerUsersRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/sales-hierarchy': {
      id: '/manager/sales-hierarchy'
      path: '/sales-hierarchy'
      fullPath: '/manager/sales-hierarchy'
      preLoaderRoute: typeof ManagerSalesHierarchyRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/pending-schools': {
      id: '/manager/pending-schools'
      path: '/pending-schools'
      fullPath: '/manager/pending-schools'
      preLoaderRoute: typeof ManagerPendingSchoolsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/onboard-school': {
      id: '/manager/onboard-school'
      path: '/onboard-school'
      fullPath: '/manager/onboard-school'
      preLoaderRoute: typeof ManagerOnboardSchoolRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/create-sales-rep': {
      id: '/manager/create-sales-rep'
      path: '/create-sales-rep'
      fullPath: '/manager/create-sales-rep'
      preLoaderRoute: typeof ManagerCreateSalesRepRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales-hierarchy': {
      id: '/admin/sales-hierarchy'
      path: '/sales-hierarchy'
      fullPath: '/admin/sales-hierarchy'
      preLoaderRoute: typeof AdminSalesHierarchyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pending-schools': {
      id: '/admin/pending-schools'
      path: '/pending-schools'
      fullPath: '/admin/pending-schools'
      preLoaderRoute: typeof AdminPendingSchoolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/directory': {
      id: '/admin/directory'
      path: '/directory'
      fullPath: '/admin/directory'
      preLoaderRoute: typeof AdminDirectoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/create-sales-rep': {
      id: '/admin/create-sales-rep'
      path: '/create-sales-rep'
      fullPath: '/admin/create-sales-rep'
      preLoaderRoute: typeof AdminCreateSalesRepRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/school-registrations': {
      id: '/api/public/school-registrations'
      path: '/api/public/school-registrations'
      fullPath: '/api/public/school-registrations'
      preLoaderRoute: typeof ApiPublicSchoolRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sales-reps': {
      id: '/api/public/sales-reps'
      path: '/api/public/sales-reps'
      fullPath: '/api/public/sales-reps'
      preLoaderRoute: typeof ApiPublicSalesRepsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCreateSalesRepRoute: typeof AdminCreateSalesRepRoute
  AdminDirectoryRoute: typeof AdminDirectoryRoute
  AdminPendingSchoolsRoute: typeof AdminPendingSchoolsRoute
  AdminSalesHierarchyRoute: typeof AdminSalesHierarchyRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCreateSalesRepRoute: AdminCreateSalesRepRoute,
  AdminDirectoryRoute: AdminDirectoryRoute,
  AdminPendingSchoolsRoute: AdminPendingSchoolsRoute,
  AdminSalesHierarchyRoute: AdminSalesHierarchyRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ManagerRouteChildren {
  ManagerCreateSalesRepRoute: typeof ManagerCreateSalesRepRoute
  ManagerOnboardSchoolRoute: typeof ManagerOnboardSchoolRoute
  ManagerPendingSchoolsRoute: typeof ManagerPendingSchoolsRoute
  ManagerSalesHierarchyRoute: typeof ManagerSalesHierarchyRoute
  ManagerUsersRoute: typeof ManagerUsersRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerCreateSalesRepRoute: ManagerCreateSalesRepRoute,
  ManagerOnboardSchoolRoute: ManagerOnboardSchoolRoute,
  ManagerPendingSchoolsRoute: ManagerPendingSchoolsRoute,
  ManagerSalesHierarchyRoute: ManagerSalesHierarchyRoute,
  ManagerUsersRoute: ManagerUsersRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

interface SchoolRouteChildren {
  SchoolBulkStudentsRoute: typeof SchoolBulkStudentsRoute
  SchoolCreateTeacherRoute: typeof SchoolCreateTeacherRoute
  SchoolIndexRoute: typeof SchoolIndexRoute
}

const SchoolRouteChildren: SchoolRouteChildren = {
  SchoolBulkStudentsRoute: SchoolBulkStudentsRoute,
  SchoolCreateTeacherRoute: SchoolCreateTeacherRoute,
  SchoolIndexRoute: SchoolIndexRoute,
}

const SchoolRouteWithChildren =
  SchoolRoute._addFileChildren(SchoolRouteChildren)

interface StudentRouteChildren {
  StudentAssignmentsRoute: typeof StudentAssignmentsRoute
  StudentQuizzesRoute: typeof StudentQuizzesRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAssignmentsRoute: StudentAssignmentsRoute,
  StudentQuizzesRoute: StudentQuizzesRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAssignmentsRoute: typeof TeacherAssignmentsRoute
  TeacherQuizzesRoute: typeof TeacherQuizzesRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAssignmentsRoute: TeacherAssignmentsRoute,
  TeacherQuizzesRoute: TeacherQuizzesRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ConsoleRoute: ConsoleRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ManagerRoute: ManagerRouteWithChildren,
  RegisterSchoolRoute: RegisterSchoolRoute,
  SalesRepRoute: SalesRepRoute,
  SchoolRoute: SchoolRouteWithChildren,
  SetupSecurityRoute: SetupSecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  LearnSlugRoute: LearnSlugRoute,
  SettingsChangePasswordRoute: SettingsChangePasswordRoute,
  ApiPublicSalesRepsRoute: ApiPublicSalesRepsRoute,
  ApiPublicSchoolRegistrationsRoute: ApiPublicSchoolRegistrationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
