/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as SalesRepRouteImport } from './routes/sales-rep'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as ManagerSalesHierarchyRouteImport } from './routes/manager.sales-hierarchy'
import { Route as ManagerOnboardSchoolRouteImport } from './routes/manager.onboard-school'
import { Route as ManagerCreateSalesRepRouteImport } from './routes/manager.create-sales-rep'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as AdminSalesHierarchyRouteImport } from './routes/admin.sales-hierarchy'
import { Route as AdminCreateSalesRepRouteImport } from './routes/admin.create-sales-rep'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRepRoute = SalesRepRouteImport.update({
  id: '/sales-rep',
  path: '/sales-rep',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerSalesHierarchyRoute = ManagerSalesHierarchyRouteImport.update({
  id: '/sales-hierarchy',
  path: '/sales-hierarchy',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerOnboardSchoolRoute = ManagerOnboardSchoolRouteImport.update({
  id: '/onboard-school',
  path: '/onboard-school',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerCreateSalesRepRoute = ManagerCreateSalesRepRouteImport.update({
  id: '/create-sales-rep',
  path: '/create-sales-rep',
  getParentRoute: () => ManagerRoute,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesHierarchyRoute = AdminSalesHierarchyRouteImport.update({
  id: '/sales-hierarchy',
  path: '/sales-hierarchy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreateSalesRepRoute = AdminCreateSalesRepRouteImport.update({
  id: '/create-sales-rep',
  path: '/create-sales-rep',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/manager': typeof ManagerRouteWithChildren
  '/sales-rep': typeof SalesRepRoute
  '/school': typeof SchoolRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRoute
  '/teacher': typeof TeacherRoute
  '/admin/create-sales-rep': typeof AdminCreateSalesRepRoute
  '/admin/sales-hierarchy': typeof AdminSalesHierarchyRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/manager/create-sales-rep': typeof ManagerCreateSalesRepRoute
  '/manager/onboard-school': typeof ManagerOnboardSchoolRoute
  '/manager/sales-hierarchy': typeof ManagerSalesHierarchyRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/sales-rep': typeof SalesRepRoute
  '/school': typeof SchoolRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRoute
  '/teacher': typeof TeacherRoute
  '/admin/create-sales-rep': typeof AdminCreateSalesRepRoute
  '/admin/sales-hierarchy': typeof AdminSalesHierarchyRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/manager/create-sales-rep': typeof ManagerCreateSalesRepRoute
  '/manager/onboard-school': typeof ManagerOnboardSchoolRoute
  '/manager/sales-hierarchy': typeof ManagerSalesHierarchyRoute
  '/manager': typeof ManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/manager': typeof ManagerRouteWithChildren
  '/sales-rep': typeof SalesRepRoute
  '/school': typeof SchoolRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRoute
  '/teacher': typeof TeacherRoute
  '/admin/create-sales-rep': typeof AdminCreateSalesRepRoute
  '/admin/sales-hierarchy': typeof AdminSalesHierarchyRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/manager/create-sales-rep': typeof ManagerCreateSalesRepRoute
  '/manager/onboard-school': typeof ManagerOnboardSchoolRoute
  '/manager/sales-hierarchy': typeof ManagerSalesHierarchyRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/console'
    | '/manager'
    | '/sales-rep'
    | '/school'
    | '/sitemap.xml'
    | '/student'
    | '/teacher'
    | '/admin/create-sales-rep'
    | '/admin/sales-hierarchy'
    | '/learn/$slug'
    | '/manager/create-sales-rep'
    | '/manager/onboard-school'
    | '/manager/sales-hierarchy'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/console'
    | '/sales-rep'
    | '/school'
    | '/sitemap.xml'
    | '/student'
    | '/teacher'
    | '/admin/create-sales-rep'
    | '/admin/sales-hierarchy'
    | '/learn/$slug'
    | '/manager/create-sales-rep'
    | '/manager/onboard-school'
    | '/manager/sales-hierarchy'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/console'
    | '/manager'
    | '/sales-rep'
    | '/school'
    | '/sitemap.xml'
    | '/student'
    | '/teacher'
    | '/admin/create-sales-rep'
    | '/admin/sales-hierarchy'
    | '/learn/$slug'
    | '/manager/create-sales-rep'
    | '/manager/onboard-school'
    | '/manager/sales-hierarchy'
    | '/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConsoleRoute: typeof ConsoleRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  SalesRepRoute: typeof SalesRepRoute
  SchoolRoute: typeof SchoolRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentRoute: typeof StudentRoute
  TeacherRoute: typeof TeacherRoute
  LearnSlugRoute: typeof LearnSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-rep': {
      id: '/sales-rep'
      path: '/sales-rep'
      fullPath: '/sales-rep'
      preLoaderRoute: typeof SalesRepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/sales-hierarchy': {
      id: '/manager/sales-hierarchy'
      path: '/sales-hierarchy'
      fullPath: '/manager/sales-hierarchy'
      preLoaderRoute: typeof ManagerSalesHierarchyRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/onboard-school': {
      id: '/manager/onboard-school'
      path: '/onboard-school'
      fullPath: '/manager/onboard-school'
      preLoaderRoute: typeof ManagerOnboardSchoolRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/create-sales-rep': {
      id: '/manager/create-sales-rep'
      path: '/create-sales-rep'
      fullPath: '/manager/create-sales-rep'
      preLoaderRoute: typeof ManagerCreateSalesRepRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales-hierarchy': {
      id: '/admin/sales-hierarchy'
      path: '/sales-hierarchy'
      fullPath: '/admin/sales-hierarchy'
      preLoaderRoute: typeof AdminSalesHierarchyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/create-sales-rep': {
      id: '/admin/create-sales-rep'
      path: '/create-sales-rep'
      fullPath: '/admin/create-sales-rep'
      preLoaderRoute: typeof AdminCreateSalesRepRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCreateSalesRepRoute: typeof AdminCreateSalesRepRoute
  AdminSalesHierarchyRoute: typeof AdminSalesHierarchyRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCreateSalesRepRoute: AdminCreateSalesRepRoute,
  AdminSalesHierarchyRoute: AdminSalesHierarchyRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ManagerRouteChildren {
  ManagerCreateSalesRepRoute: typeof ManagerCreateSalesRepRoute
  ManagerOnboardSchoolRoute: typeof ManagerOnboardSchoolRoute
  ManagerSalesHierarchyRoute: typeof ManagerSalesHierarchyRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerCreateSalesRepRoute: ManagerCreateSalesRepRoute,
  ManagerOnboardSchoolRoute: ManagerOnboardSchoolRoute,
  ManagerSalesHierarchyRoute: ManagerSalesHierarchyRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ConsoleRoute: ConsoleRoute,
  ManagerRoute: ManagerRouteWithChildren,
  SalesRepRoute: SalesRepRoute,
  SchoolRoute: SchoolRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentRoute: StudentRoute,
  TeacherRoute: TeacherRoute,
  LearnSlugRoute: LearnSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
