ALTER TABLE public.audit_logs
  ADD COLUMN IF NOT EXISTS audit_ref bigint GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS module text,
  ADD COLUMN IF NOT EXISTS target_role text,
  ADD COLUMN IF NOT EXISTS target_user_id uuid;

CREATE INDEX IF NOT EXISTS audit_logs_module_idx ON public.audit_logs (module);
CREATE INDEX IF NOT EXISTS audit_logs_status_idx ON public.audit_logs (status);
CREATE INDEX IF NOT EXISTS audit_logs_target_idx ON public.audit_logs (target_user_id);
CREATE INDEX IF NOT EXISTS audit_logs_ref_idx ON public.audit_logs (audit_ref DESC);

DROP POLICY IF EXISTS "admins read audit" ON public.audit_logs;
CREATE POLICY "admins and managers read audit"
  ON public.audit_logs FOR SELECT TO authenticated
  USING (
    private.has_role(auth.uid(), 'admin'::app_role)
    OR private.has_role(auth.uid(), 'portal_manager'::app_role)
  );